services:
  blogapp:
    image: ${DOCKER_REGISTRY-}blogapp
    build:
      context: BlogAPP
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081" 
    depends_on:
      - sql
      - redis 
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server2022
    ports: 
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=Password1
    volumes:
      - sqlserver_data:/var/opt/mssql
   
  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - 90:6379

volumes:
  sqlserver_data: 
    driver: local 